from pydantic import BaseModel, Field
from typing import List


class DefineStrategyFrameworkOutput(BaseModel):
    """Pydantic model for define_strategy_framework node outputs."""
    strategy_type: str = (
        Field(..., description="High-level category of the strategy (e.g., statistical arbitrage, trend following, mean reversion)")
    )
    defining_characteristics: List[str] = (
        Field(..., description="3-5 concise bullet points that capture the core attributes of the strategy")
    )
    signal_generation_methodology: str = (
        Field(..., description="Brief description of how trading signals are generated within the framework")
    )
    position_sizing_approach: str = (
        Field(..., description="Summary of the position sizing rules and risk allocation logic")
    )
    execution_protocols: str = (
        Field(..., description="Overview of order execution tactics, including order types and routing preferences")
    )
    framework_summary: str = (
        Field(..., description="Full 250-word description combining all elements of the framework")
    )


def define_strategy_framework(general_input: str, **kwargs) -> DefineStrategyFrameworkOutput:
    """
    Generate a complete quantitative strategy framework description.

    Returns
    -------
    dict
        Dictionary containing six keys: strategy_type (str),
        defining_characteristics (List[str]), signal_generation_methodology
        (str), position_sizing_approach (str), execution_protocols (str),
        and framework_summary (str).

    Raises
    ------
    RuntimeError
        If internal logic fails to produce any of the required output
        fields.

    Examples
    --------
    >>> framework = define_strategy_framework()
    >>> print(framework['strategy_type'])
    >>> print(framework['defining_characteristics'])
    >>> print(framework['framework_summary'][:60])  # first 60 chars
    statistical_arbitrage
    ['Mean‑reversion of mispricings', 'High‑frequency execution', 'Risk‑scaled
    exposure']
    'Statistical arbitrage strategy that exploits short‑term price deviations
    ...'

    >>> framework = define_strategy_framework()
    >>> for key, value in framework.items():
    ...     print(f"{key}: {value}")
    strategy_type: statistical_arbitrage
    "
                            + "defining_characteristics: ['Mean‑reversion of
    mispricings', 'High‑frequency execution', 'Risk‑scaled exposure']
    "
                            + "signal_generation_methodology: Signals are
    generated by applying a linear regression model to a ranked set of
    liquidity‑adjusted features and triggering entry when the predicted residual
    exceeds a dynamic threshold.
    "
                            + "position_sizing_approach: Position size is
    proportional to the inverse of recent realized volatility, capped by a
    VaR‑based max exposure and adjusted for available order‑book depth.
    "
                            + "execution_protocols: Uses a hybrid market/limit
    order strategy routed through low‑latency gateways, with batch slicing
    during high‑impact windows.
    "
                            + "framework_summary: Statistical arbitrage strategy
    that exploits short‑term price deviations across correlated futures
    contracts. Signals are derived from a regression‑based model that ingests
    liquidity‑adjusted features such as order‑book imbalance, recent price
    momentum, and macro‑factor spreads. Positions are sized using a
    volatility‑scaled multiplier, constrained by portfolio VaR limits and
    real‑time depth thresholds. Execution combines aggressive market orders for
    small, high‑confidence signals and passive limit orders with price‑time
    priority for larger exposures, routed through the nearest exchange gateway
    to minimize latency. The framework emphasizes tight risk controls, adaptive
    sizing, and robust back‑testing across multiple market regimes.

    """
    return DefineStrategyFrameworkOutput(
        strategy_type="",
        defining_characteristics=[],
        signal_generation_methodology="",
        position_sizing_approach="",
        execution_protocols="",
        framework_summary="",
    )